# Generated by Django 3.2.7 on 2022-02-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
