# Generated by Django 3.2.7 on 2022-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220201_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
