# Generated by Django 3.2.7 on 2022-02-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220201_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='storyline',
            field=models.TextField(max_length=300),
        ),
    ]
